/// Get 
GET http://localhost:3000/profile

### Login
POST http://localhost:3030/api/login
Content-Type: application/json

{
    "user": "root",
    "password": "admin"
}

### refresh-token
POST http://localhost:3000/refresh-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjBibEJLMHdVVHFBSzhfMFlQY0VpVSJ9.eyJpc3MiOiJodHRwczovL2Rldi14YXVwNnZmdGRhYTVhbm4zLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI4N1BzVXltOGxubktkTHNjclozU0dCdllveFUwS29KVUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLWFwaS8iLCJpYXQiOjE3MjcyMzQwNjksImV4cCI6MTcyNzMyMDQ2OSwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiODdQc1V5bThsbm5LZExzY3JaM1NHQnZZb3hVMEtvSlUifQ.gw_FcczwqjPL8z_wHc6pEI8IGi12fRieSfoJx1yEQZLelXbQsZMUYmAdd28xdTl-3ZD_OuyU5OgwBoUgfoG3ICS0JHcpX4XC2pf_FihiB2sAHIKp0lTFE8QqL_qDMvUQRW9Xl5oSO4iCJxgltLqBuXNeDUxkoHj_LpsToqHnmicrKTgHMN1ryveDFnWmvyzScbSobxtcq4xscVSpFKBCn5hCR95u6wKrCjq85ea4me5oa7Wv6eaHVpcwXUvXfimq3Fs0cEg8Xv-JJZ3mMyQc27PfNb4O61bJxdpJg3ijOqKvLmSScK5FAe9Bp1VHeQR8XIFCD2-RAeD0A4M9uSvLoA

### Get private
GET http://localhost:3000/private
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjBibEJLMHdVVHFBSzhfMFlQY0VpVSJ9.eyJpc3MiOiJodHRwczovL2Rldi14YXVwNnZmdGRhYTVhbm4zLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI4N1BzVXltOGxubktkTHNjclozU0dCdllveFUwS29KVUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLWFwaS8iLCJpYXQiOjE3MjY1NDIyMjIsImV4cCI6MTcyNjYyODYyMiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiODdQc1V5bThsbm5LZExzY3JaM1NHQnZZb3hVMEtvSlUifQ.Co7GOHpdueOToOjg_50cA2vpf_Q7hS7Zw1jc7543-i0eNsgdJJOtLzM0gTSX4X85GLpKL0OuRy7rMhad0NF5MR7uNra9kPseC5x4_jnQ_UmDmldWDkmNeqeTUDya-ll3cXnQhplKU7DKOWmO1vA_-Cl0VknDCON1fs_cuc75LdFEt0MBi0mjCysDaHC8u9ndvp7fIOz-DPvkroazB5ZpfYvR4_6QJyyn4FVaHmEGoIuaM5LvqWcQWAlIm6DO4rb2oOz-36QSNFs5fZGt6DmDi1L36MRdpFZyCZwA389LWlS4OlzV39XzpqlN3jPN8Ldts1ihRYfPmQwjx5m02Mts4Q

### Logout
GET http://localhost:3030/api/private

### Logout
POST http://localhost:3030/api/logout

### Logout
GET http://localhost:3030/api/check-auth